import type { UnifiedCommand } from "./types";

export const videoGenerateCommand: UnifiedCommand = {
  action: "video-generate",
  submitLabel: "Generate Video",
  runningLabel: "Generating...",
  fields: [
    { key: "prompt", cliFlag: "--prompt", control: "prompt" },
    { key: "test_prompt", cliFlag: "--test-prompt", control: "text", label: "Test Prompt" },
    { key: "width", cliFlag: "--width", control: "number", label: "Width", default: 704 },
    { key: "height", cliFlag: "--height", control: "number", label: "Height", default: 448 },
    { key: "frames", cliFlag: "--frames", control: "number", label: "Frames", default: 97 },
    { key: "fps", cliFlag: "--fps", control: "number", label: "FPS", default: 24 },
    { key: "input_image", cliFlag: "--input-image", control: "image", label: "Input Image" },
    { key: "audio", cliFlag: "--audio", control: "text", label: "Audio" },
    { key: "begin_image", cliFlag: "--begin-image", control: "image", label: "Begin Image" },
    { key: "end_image", cliFlag: "--end-image", control: "image", label: "End Image" },
    { key: "begin_strength", cliFlag: "--begin-strength", control: "range", label: "Begin Strength", default: 1.0, min: 0, max: 1 },
    { key: "end_strength", cliFlag: "--end-strength", control: "range", label: "End Strength", default: 1.0, min: 0, max: 1 },
    { key: "seed", cliFlag: "--seed", control: "number", label: "Seed", default: 42 },
    { key: "cfg_scale", cliFlag: "--cfg-scale", control: "number", label: "CFG Scale", default: 5.0 },
    { key: "stg_scale", cliFlag: "--stg-scale", control: "number", label: "STG Scale", default: 1.0 },
    { key: "stage1_steps", cliFlag: "--stage1-steps", control: "number", label: "Stage 1 Steps" },
    { key: "stage2_steps", cliFlag: "--stage2-steps", control: "number", label: "Stage 2 Steps" },
    { key: "low_ram", cliFlag: "--low-ram", control: "toggle", label: "Low RAM" },
    { key: "hq", cliFlag: "--hq", control: "toggle", label: "HQ" },
    { key: "distilled", cliFlag: "--distilled", control: "toggle", label: "Distilled" },
    { key: "teacache", cliFlag: "--teacache", control: "toggle", label: "TeaCache" },
    { key: "teacache_thresh", cliFlag: "--teacache-thresh", control: "number", label: "TeaCache Threshold" },
    { key: "temporal_upscale", cliFlag: "--temporal-upscale", control: "toggle", label: "Temporal Upscale" },
    { key: "enhance_prompt", cliFlag: "--enhance-prompt", control: "toggle", label: "Enhance Prompt" },
    { key: "lora_path", cliFlag: "--lora-path", control: "text", label: "LoRA Path" },
    { key: "lora_scale", cliFlag: "--lora-scale", control: "range", label: "LoRA Scale", default: 1.0 },
  ],
};
