import type { CommandSchema } from "./shared";
import { PROMPT, SEED, LORA_PATH, LORA_SCALE } from "./shared";

export const videoGenerate: CommandSchema = {
  prompt: PROMPT,
  test_prompt: { type: "string", cliFlag: "--test-prompt" },
  width: { type: "number", cliFlag: "--width", default: 704 },
  height: { type: "number", cliFlag: "--height", default: 448 },
  frames: { type: "number", cliFlag: "--frames", default: 97 },
  fps: { type: "number", cliFlag: "--fps", default: 24 },
  input_image: { type: "string", cliFlag: "--input-image" },
  audio: { type: "string", cliFlag: "--audio" },
  begin_image: { type: "string", cliFlag: "--begin-image" },
  end_image: { type: "string", cliFlag: "--end-image" },
  begin_strength: { type: "number", cliFlag: "--begin-strength", default: 1.0, min: 0, max: 1 },
  end_strength: { type: "number", cliFlag: "--end-strength", default: 1.0, min: 0, max: 1 },
  seed: SEED,
  cfg_scale: { type: "number", cliFlag: "--cfg-scale", default: 5.0 },
  stg_scale: { type: "number", cliFlag: "--stg-scale", default: 1.0 },
  stage1_steps: { type: "number", cliFlag: "--stage1-steps" },
  stage2_steps: { type: "number", cliFlag: "--stage2-steps" },
  low_ram: { type: "boolean", cliFlag: "--low-ram" },
  hq: { type: "boolean", cliFlag: "--hq" },
  distilled: { type: "boolean", cliFlag: "--distilled" },
  teacache: { type: "boolean", cliFlag: "--teacache" },
  teacache_thresh: { type: "number", cliFlag: "--teacache-thresh" },
  temporal_upscale: { type: "boolean", cliFlag: "--temporal-upscale" },
  enhance_prompt: { type: "boolean", cliFlag: "--enhance-prompt" },
  lora_path: LORA_PATH,
  lora_scale: LORA_SCALE,
};
