#!/usr/bin/env bash
# sweep_dasiwa_voice_tune.sh — find the best AUDIO config for dasiwa.
#
# The voice A/B (a7364c9) confirmed 16 steps reliably intelligible, but held the
# audio-specific knobs fixed and never asked *which audio config is best*. This
# sweep isolates the two never-tested audio knobs at the voice sweet spot:
#
#   base (held constant): dasiwa · 16 stage1-steps · 57 frames · optimized prompt
#                         · cfg 5 · seed 42 · 768x512 · --low-ram · --first-frame
#   axis A:  --audio-cfg-scale   {None (vendor ~7), 3.0, 5.0}
#   axis B:  --audio-stage1-only {off, on}   (skip stage-2 audio refinement,
#                                             upstream LTX-2 issue #126 hint)
#
#   C1  cfg=default · stage1-only=off   ← reuses the existing dasiwa-16st-opt mp4
#   C2  cfg=3.0     · off
#   C3  cfg=5.0     · off
#   C4  cfg=default · on
#   C5  cfg=3.0     · on
#   C6  cfg=5.0     · on
#
# C1 is the base config already generated by sweep_voice.sh, so we reuse it
# (only 5 NEW GPU cells). Logs 7-col rows to output/.voice_tune_runs.txt for
# build_voice_review.py. Sequential (GPU lock). ~17 min total.
#
# Usage:
#   bash scripts/sweep_dasiwa_voice_tune.sh
# Resume: re-running rewrites the log — comment out done cells, or re-run all.

set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
PY=/Users/huangziyu/proj/video_generation/python/venv/bin/python
OPT_PROMPT=/tmp/voice-optimized.txt
PREV_RUNS="output/.voice_runs.txt"
RUNS_LOG="output/.voice_tune_runs.txt"
SWEEP_LOG="output/.sweep_voice_tune.log"

mkdir -p output
: > "$RUNS_LOG"
: > "$SWEEP_LOG"

if [ ! -f "$OPT_PROMPT" ]; then
  echo "ERROR: optimized prompt file not found: $OPT_PROMPT" >&2; exit 1
fi

log_run() {  # <mp4> <label> <tag>
  echo "$1|$2|dasiwa|16|5|$3|tune" >> "$RUNS_LOG"
}

run_cell() {  # <label> <tag> <audio_cfg_or_-> <stage1_only:0|1>
  local label="$1" tag="$2" cfg="$3" s1only="$4"
  local desc="cfg=${cfg/-/default} stage1-only=${s1only}"
  echo "====================================================================" | tee -a "$SWEEP_LOG"
  echo ">>> [$label]  $desc" | tee -a "$SWEEP_LOG"
  local logf="/tmp/voice_tune_${label}.log"
  local args=(--transformer dasiwa --prompt-file "$OPT_PROMPT"
              --width 768 --height 512 --frames 57 --fps 24 --seed 42
              --stage1-steps 16 --cfg-scale 5 --first-frame --low-ram -y)
  [ "$cfg" != "-" ] && args+=(--audio-cfg-scale "$cfg")
  [ "$s1only" = "1" ] && args+=(--audio-stage1-only)
  if "$PY" run.py video generate "${args[@]}" > "$logf" 2>&1; then
    local base
    base="$(grep -oE 'Saved:[[:space:]]+\S+\.mp4' "$logf" | head -1 | sed -E 's/Saved:[[:space:]]+//')"
    if [ -n "$base" ]; then
      log_run "$base" "$label" "$tag"
      echo "  ✅ $label -> $(basename "$base")" | tee -a "$SWEEP_LOG"
    else
      echo "  ⚠️  $label: ran but no Saved line found (see $logf)" | tee -a "$SWEEP_LOG"
    fi
  else
    echo "  ❌ $label FAILED (see $logf)" | tee -a "$SWEEP_LOG"
    tail -8 "$logf" >> "$SWEEP_LOG"
  fi
}

# --- C1: reuse the existing dasiwa-16st-opt (base config, no audio-knob override) ---
C1_MP4="$(grep '|dasiwa-16st-opt|' "$PREV_RUNS" 2>/dev/null | head -1 | cut -d'|' -f1)"
if [ -n "$C1_MP4" ] && [ -f "$C1_MP4" ]; then
  log_run "$C1_MP4" "dasiwa-cfgD-s2off" "cfgD-s2off"
  echo "  ♻️  C1 reused existing dasiwa-16st-opt -> $(basename "$C1_MP4")" | tee -a "$SWEEP_LOG"
else
  echo "  ⚠️  C1 base not found in $PREV_RUNS — generating it" | tee -a "$SWEEP_LOG"
  run_cell "dasiwa-cfgD-s2off" "cfgD-s2off" "-" 0
fi

# --- C2–C6: the 5 new audio-knob combinations ---
run_cell "dasiwa-cfg3-s2off" "cfg3-s2off" "3.0" 0
run_cell "dasiwa-cfg5-s2off" "cfg5-s2off" "5.0" 0
run_cell "dasiwa-cfgD-s1on"  "cfgD-s1on"  "-"   1
run_cell "dasiwa-cfg3-s1on"  "cfg3-s1on"  "3.0" 1
run_cell "dasiwa-cfg5-s1on"  "cfg5-s1on"  "5.0" 1

echo "====================================================================" | tee -a "$SWEEP_LOG"
echo "🎉 VOICE TUNE SWEEP DONE: $(wc -l < "$RUNS_LOG") / 6 runs logged -> $RUNS_LOG" | tee -a "$SWEEP_LOG"
echo "    Next: $PY scripts/build_voice_review.py --runs $RUNS_LOG" | tee -a "$SWEEP_LOG"
