/**
 * Build pipeline for pi-agent.
 *
 * Tiers:
 *   bun scripts/build.ts            bundle + minify + external sourcemap
 *   bun scripts/build.ts --compile  bun --compile → standalone executable
 *   bun scripts/build.ts --all      bundle + compile
 *
 * Output (repo root dist/, namespaced):
 *   ../../dist/pi-agent/pi-agent.js      bundled entry (minified)
 *   ../../dist/pi-agent/pi-agent.js.map  sourcemap (debug only — embeds full source)
 *   ../../dist/pi-agent/pi-agent         standalone executable (--compile only)
 *   ../../dist/pi-agent/theme/           asset dir copied alongside binary
 *   ../../dist/pi-agent/export-html/     asset dir copied alongside binary
 *   ../../dist/pi-agent/assets/          asset dir copied alongside binary
 *
 * Asset handling (two separate mechanisms):
 *
 *   Bundle (.js): pi's getPackageDir() walks up from __dirname and wrongly
 *   finds the monorepo root instead of pi-coding-agent. We resolve the real
 *   package dir at build time and bake it into src/generated/pi-pkg-dir.ts,
 *   which the set-package-dir patch reads and sets as PI_PACKAGE_DIR.
 *
 *   Binary: pi's isBunBinary flag is true, so getPackageDir() = dirname(exe).
 *   We copy theme/, export-html/, and assets/ alongside the exe.
 */
import {
  appendFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, resolve } from "node:path";

const APP_NAME: string = basename(process.cwd()); // "pi-agent"
const ENTRY = "src/cli.ts";
const GENERATED_DIR = "src/generated";
const GENERATED_PKG_DIR = `${GENERATED_DIR}/pi-pkg-dir.ts`;
const OUTDIR = resolve(process.cwd(), "..", "..", "dist", APP_NAME);
const OUTFILE = `${OUTDIR}/${APP_NAME}.js`;
const MAPFILE = `${OUTFILE}.map`;
const EXE = `${OUTDIR}/${APP_NAME}`;

const argv = process.argv.slice(2);
const DO_COMPILE = argv.includes("--compile") || argv.includes("--all");

function ensureOutdir() {
  if (!existsSync(OUTDIR)) mkdirSync(OUTDIR, { recursive: true });
  if (!existsSync(GENERATED_DIR)) mkdirSync(GENERATED_DIR, { recursive: true });
}

function clean(...files: string[]) {
  for (const f of files) if (existsSync(f)) rmSync(f, { recursive: true });
}

// ── Resolve pi-coding-agent package directory ─────────────────────────────────
// Bun resolves this relative to the build script's location (bun-apps/pi-agent/).
// The result is the absolute path to the pi-coding-agent package in node_modules.
function resolvePiPkgDir(): string {
  const pkgJsonUrl = import.meta.resolve("@earendil-works/pi-coding-agent/package.json");
  return dirname(new URL(pkgJsonUrl).pathname);
}

// ── Stage 0: generate PI_PKG_DIR constant ────────────────────────────────────
function stageGeneratePkgDir(piPkgDir: string) {
  console.log(`▶ generate src/generated/pi-pkg-dir.ts`);
  ensureOutdir();
  writeFileSync(
    GENERATED_PKG_DIR,
    `// AUTO-GENERATED by scripts/build.ts — do not edit or commit\n` +
    `// Points the set-package-dir patch at the real pi-coding-agent in node_modules.\n` +
    `export const PI_PKG_DIR = ${JSON.stringify(piPkgDir)};\n`,
  );
  console.log(`  ✓ PI_PKG_DIR = ${piPkgDir}`);
}

// ── Stage 1: bundle + minify ─────────────────────────────────────────────────
async function stageBundle() {
  console.log(`▶ bundle + minify → dist/${APP_NAME}/${APP_NAME}.js`);
  clean(OUTFILE, MAPFILE, EXE);

  const { build } = await import("bun");
  const result = await build({
    entrypoints: [ENTRY],
    outdir: OUTDIR,
    target: "bun",
    format: "esm",
    naming: `${APP_NAME}.js`,
    minify: { whitespace: true, identifiers: true, syntax: true },
    sourcemap: "external",
    splitting: false,
  });

  if (!result.success) {
    for (const l of result.logs) console.error(l);
    process.exit(1);
  }

  appendFileSync(OUTFILE, `\n//# sourceMappingURL=${APP_NAME}.js.map\n`);
  console.log(`  ✓ ${OUTFILE}  (${formatSize(OUTFILE)})`);
  console.log(`  ✓ ${MAPFILE}`);
}

// ── Stage 2: compile to standalone executable ─────────────────────────────────
async function stageCompile() {
  console.log(`▶ compile → dist/${APP_NAME}/${APP_NAME}  (standalone binary)`);
  clean(EXE);
  const proc = Bun.spawn(
    ["bun", "build", OUTFILE, "--compile", `--outfile=${EXE}`, "--minify"],
    { stdout: "inherit", stderr: "inherit" },
  );
  const code = await proc.exited;
  if (code !== 0) {
    console.error(`  ✗ bun build --compile exited ${code}`);
    process.exit(code);
  }
  console.log(`  ✓ ${EXE}  (${formatSize(EXE)})`);
}

// ── Stage 3: copy assets alongside the binary ────────────────────────────────
// pi's isBunBinary path expects these dirs next to the executable.
// getThemesDir()       → <exe-dir>/theme/
// getExportTemplateDir → <exe-dir>/export-html/
// getAssetsDir()       → <exe-dir>/assets/
function stageCopyAssets(piPkgDir: string) {
  console.log(`▶ copy pi assets alongside binary`);
  const assetMap: Array<[string, string]> = [
    [`${piPkgDir}/dist/modes/interactive/theme`, `${OUTDIR}/theme`],
    [`${piPkgDir}/dist/core/export-html`, `${OUTDIR}/export-html`],
    [`${piPkgDir}/dist/modes/interactive/assets`, `${OUTDIR}/assets`],
  ];
  for (const [src, dst] of assetMap) {
    if (!existsSync(src)) {
      console.log(`  · skipping ${basename(dst)}/ (not found in pi package)`);
      continue;
    }
    if (existsSync(dst)) rmSync(dst, { recursive: true });
    cpSync(src, dst, { recursive: true });
    console.log(`  ✓ ${basename(dst)}/`);
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatSize(path: string): string {
  try {
    const bytes = Bun.file(path).size;
    if (bytes > 1_000_000) return `${(bytes / 1_000_000).toFixed(1)} MB`;
    if (bytes > 1_000) return `${(bytes / 1_000).toFixed(0)} KB`;
    return `${bytes} B`;
  } catch {
    return "?";
  }
}

// ── Orchestrate ───────────────────────────────────────────────────────────────

const piPkgDir = resolvePiPkgDir();
stageGeneratePkgDir(piPkgDir);
await stageBundle();
if (DO_COMPILE) {
  await stageCompile();
  stageCopyAssets(piPkgDir);
}
// Clean up generated file — it's only needed during bundling.
clean(GENERATED_PKG_DIR);

console.log("▶ done");
if (existsSync(MAPFILE)) {
  console.log("");
  console.log("  ⚠  sourcemap present — contains full original source.");
  console.log("     Remove before shipping:  rm dist/pi-agent/pi-agent.js.map");
}
