/**
 * generate-embedded-assets.ts — build-time codegen for the --compile-embed
 * binary mode.
 *
 * Walks the exact same source directories that stageCopyAssets() copies today,
 * and writes src/generated/embedded-assets.ts with a `type: "file"` import per
 * file, plus a typed manifest array mapping relPath → blobPath.
 *
 * When run WITHOUT embedMode=true (zero-files pass), writes an empty manifest
 * with no imports — used for classic --compile and bundle-only builds so the
 * generated file is always present (the extract-embedded-assets patch does a
 * static import and must not crash at compile time).
 */
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

/** JS/TS source file extensions that should NOT be embedded via type:file.
 *  These are JavaScript modules that pi imports as regular modules, and
 *  embedding them via type:file plus having them as module imports confuses
 *  Bun's bundler. Affects export-html/ JS modules and their
 *  sourcemaps/declarations. EXCEPTION: see isRuntimeReadClientScript. */
const CODE_EXTS = new Set(["js", "mjs", "cjs", "ts", "mts", "cts"]);

/** Client-side scripts pi reads at RUNTIME via readFileSync, not ES modules.
 *  generateHtml() (pi-coding-agent dist/core/export-html/index.js) reads
 *  template.js + vendor/marked.min.js + vendor/highlight.min.js from
 *  getExportTemplateDir() — which in binary mode is the extraction cache this
 *  manifest populates. Dropping them (the old blanket .js filter) made
 *  binary-mode /export fail with ENOENT on template.js. index.js /
 *  ansi-to-html.js / tool-renderer.js stay excluded: they are real ES modules
 *  already bundled into the binary. */
function isRuntimeReadClientScript(relRoot: string, rel: string): boolean {
	return relRoot === "export-html" && (rel === "template.js" || rel.startsWith("vendor/"));
}

export interface EmbeddedAssetEntry {
  relPath: string;
  absPath: string;
}

/**
 * Recursively walk a directory and return all files as EmbeddedAssetEntry[].
 * relPath is computed relative to `basePrefix` (the source root for this dir).
 */
function walkDir(dir: string, basePrefix: string): EmbeddedAssetEntry[] {
  const entries: EmbeddedAssetEntry[] = [];
  if (!existsSync(dir)) return entries;

  const collect = (currentDir: string) => {
    for (const name of readdirSync(currentDir)) {
      const full = join(currentDir, name);
      const st = statSync(full);
      if (st.isDirectory()) {
        collect(full);
      } else if (st.isFile()) {
        entries.push({
          relPath: relative(basePrefix, full),
          absPath: full,
        });
      }
    }
  };
  collect(dir);
  return entries;
}

/**
 * Generate src/generated/embedded-assets.ts.
 *
 * @param piPkgDir    Absolute path to @earendil-works/pi-coding-agent's package dir
 * @param bunAppsDir  Absolute path to bun-apps/
 * @param binarySkills List of skill dir relpaths from manifest.json's binarySkills
 * @param embedMode   true → emit `type: "file"` imports; false → empty manifest
 */
export function generateEmbeddedAssets(
  piPkgDir: string,
  bunAppsDir: string,
  binarySkills: string[],
  embedMode: boolean,
): void {
  // ── Collect all files from the same source dirs as stageCopyAssets() ──────
  const assetMap: Array<{ sourceDir: string; relRoot: string }> = [
    { sourceDir: join(piPkgDir, "dist", "modes", "interactive", "theme"), relRoot: "theme" },
    { sourceDir: join(piPkgDir, "dist", "core", "export-html"), relRoot: "export-html" },
    { sourceDir: join(piPkgDir, "dist", "modes", "interactive", "assets"), relRoot: "assets" },
    // Binary skills — each is a dir like "s2-agent-ext-superpowers/skills"
    ...binarySkills.map((rel) => ({
      sourceDir: join(bunAppsDir, rel),
      relRoot: rel,
    })),
  ];

  const allFiles: Array<{ relPath: string; absPath: string }> = [];
  for (const { sourceDir, relRoot } of assetMap) {
    if (!existsSync(sourceDir)) continue;
    for (const entry of walkDir(sourceDir, sourceDir)) {
      // Code-ext filter lives HERE (not in walkDir) because the runtime-read
      // exception needs relRoot context. relPath uses "/" separators on all
      // platforms (path.join replaced below), so startsWith("vendor/") is safe.
      const ext = entry.relPath.split(".").pop()?.toLowerCase() ?? "";
      if (CODE_EXTS.has(ext) && !isRuntimeReadClientScript(relRoot, entry.relPath)) continue;
      allFiles.push({
        relPath: join(relRoot, entry.relPath),
        absPath: entry.absPath,
      });
    }
  }

  // ── Build file content ────────────────────────────────────────────────────
  let output = "// AUTO-GENERATED by scripts/generate-embedded-assets.ts — do not edit or commit\n";
  output += "// Embedded asset manifest for --compile-embed binary mode.\n\n";

  if (embedMode && allFiles.length > 0) {
    // Emit one `type: "file"` import per file, with short unique variable names
    for (let i = 0; i < allFiles.length; i++) {
      const escPath = allFiles[i]!.absPath.replace(/\\/g, "/");
      output += `import a${i} from ${JSON.stringify(escPath)} with { type: "file" };\n`;
    }
    output += "\n";
    output += "export const EMBEDDED_ASSETS: Array<{ relPath: string; blobPath: string }> = [\n";
    for (let i = 0; i < allFiles.length; i++) {
      const rel = allFiles[i]!.relPath.replace(/\\/g, "/");
      output += `  { relPath: ${JSON.stringify(rel)}, blobPath: a${i} },\n`;
    }
    output += "];\n";
  } else {
    // Non-embed build: empty manifest, no imports.
    output += "export const EMBEDDED_ASSETS: Array<{ relPath: string; blobPath: string }> = [];\n";
  }

  const outFile = join(bunAppsDir, "s2-agent", "src", "generated", "embedded-assets.ts");
  writeFileSync(outFile, output, "utf8");
  // Progress line, and the sh deploy runs this under deploy-cli — which
  // promises stdout is PURE JSON. stderr is where progress belongs.
  console.error(`  ✓ embedded-assets.ts  (${allFiles.length} files${embedMode ? ", embedded" : ", empty manifest"})`);
}
