// Single-source card format helpers (dedup ticket hermes-arch-12; from audit ticket 05 findings K4-K9)
import { readFileSync } from "node:fs";
import { parseFrontmatter } from "@repo/pi-agent-ext-obsidian/extensions/obsidian.ts";

/** Minimal YAML scalar renderer. Lifted verbatim from ingest.ts (was the
 *  local `yamlScalar` there); ingest imports it back for renderFrontmatter /
 *  renderRelationsBlock. */
export function yamlScalar(v: unknown): string {
	const s = String(v);
	// Quote if it contains chars that would confuse parseFrontmatter's scalar
	// stripper (colon, bracket, leading quote, etc).
	if (/[:\[\]#"']/.test(s) || s.includes(", ")) return JSON.stringify(s);
	return s;
}

/** Read a card file's frontmatter tags (normalised) + source_id + feature
 *  flags, for link computation, collision detection, and feature-aware
 *  retrieval ranking. Returns null if not a valid card. Feature keys are
 *  ADDITIVE (old cards just lack them → hasCallouts:false, backward-compatible).
 *  Moved verbatim from ingest.ts (single-source card format helpers); ingest
 *  re-exports it (tests import it from ingest.ts) and imports it for its
 *  internal call sites. */
export function readCardMeta(absPath: string): {
	tags: Set<string>;
	source_id?: string;
	source?: string;
	hasCallouts: boolean;
	calloutTypes: string[];
} | null {
	try {
		const content = readFileSync(absPath, "utf8");
		const { data } = parseFrontmatter(content);
		if (!data || !Array.isArray(data.tags)) return null;
		const tags = new Set(
			(data.tags as unknown[]).map((t) => normTag(String(t))),
		);
		const hasCallouts = data.has_callouts === true;
		const calloutTypes = Array.isArray(data.callout_types)
			? (data.callout_types as unknown[]).map((t) => String(t).toLowerCase())
			: [];
		return {
			tags,
			source_id: typeof data.source_id === "string" ? data.source_id : undefined,
			source: typeof data.source === "string" ? data.source : undefined,
			hasCallouts,
			calloutTypes,
		};
	} catch {
		return null;
	}
}

/** Union card-frontmatter field extractor: pull the lifecycle + provenance
 *  fields off parsed frontmatter in ONE place. Deliberately default-light —
 *  only `id` ("" fallback), `status` ("active" fallback, trimmed), and
 *  `confidence` (0 fallback) get defaults; every other field passes through
 *  as-is so call-site narrowing stays at the call sites. */
export function readCardFrontmatterFields(content: string) {
	const { data } = parseFrontmatter(content);
	return {
		id: data.id ?? "",
		created: data.created,
		tags: data.tags,
		sourceId: data.source_id,
		source: data.source,
		recordType: data.record_type,
		status: (data.status ?? "active").trim(),
		supersededBy: data.superseded_by,
		confidence: typeof data.confidence === "number" ? data.confidence : 0,
	};
}

/** Card anatomy: the H1 title + the `## 核心想法` section body — the exact
 *  shape ingest's tokeniseCardFile computed inline before this single-source
 *  helper existed. */
export function cardAnatomy(content: string): { title: string; body: string } {
	const titleMatch = content.match(/^#\s+(.+?)\s*$/m);
	const title = titleMatch ? titleMatch[1]! : "";
	const bodyMatch = content.match(/## 核心想法\n([\s\S]*?)(?=\n## )/);
	const body = bodyMatch ? bodyMatch[1]! : "";
	return { title, body };
}

/** Pure MOC content builder — lifted verbatim from ingest.ts's writeMoc so the
 *  output is byte-identical. Groups cards by record-type tag (tags[1], "other"
 *  fallback), sorted lists, fully deterministic. writeMoc owns the
 *  join/mkdir/writeFileSync tail. */
export function buildMocContent(cardsAbs: string[]): string {
	const groups = new Map<string, string[]>(); // group-key -> list of card names
	for (const abs of cardsAbs) {
		const meta = readCardMeta(abs);
		if (!meta) continue;
		const base = abs.slice(abs.lastIndexOf("/") + 1, -3); // strip ".md"
		// Group by the type tag if present (tags[1]); else "other".
		let type = "other";
		const typeTag = [...meta.tags][1];
		if (typeTag && typeTag !== "zettel") type = typeTag;
		if (!groups.has(type)) groups.set(type, []);
		groups.get(type)!.push(base);
	}
	for (const list of groups.values()) list.sort();

	const order = ["gotcha", "avoid", "lever", "pattern", "metric", "false_positive", "other"];
	const present = order.filter((g) => groups.has(g)).concat(
		[...groups.keys()].filter((g) => !order.includes(g)).sort(),
	);
	const lines: string[] = [
		"---",
		"id: knowledge-graph-moc",
		'created: "auto"',
		"tags: [zettel, moc, knowledge-graph]",
		"---",
		"",
		"# Knowledge Graph — Converged Cards MOC",
		"",
		"> Auto-generated by `zk_ingest`. Do not edit by hand — regenerate with a re-ingest.",
		"> One card per structured knowledge record, dedup'd by canonical id, cross-linked by shared tags.",
		"",
	];
	for (const g of present) {
		lines.push(`## ${g}`);
		lines.push("");
		for (const name of groups.get(g)!) lines.push(`- [[${name}]]`);
		lines.push("");
	}
	// Aggregation section (ticket 03): link only TOP-layer derived nodes
	// (multi-level tree entry points; lower levels reachable through their
	// 子節點 links).
	const aggNames = cardsAbs
		.map((abs) => abs.slice(abs.lastIndexOf("/") + 1, -3))
		.filter((b) => /^agg-L\d+-\d+$/.test(b));
	if (aggNames.length > 0) {
		const maxLayer = Math.max(...aggNames.map((b) => Number(/^agg-L(\d+)-/.exec(b)![1])));
		lines.push("## aggregation", "");
		for (const n of aggNames.filter((b) => Number(/^agg-L(\d+)-/.exec(b)![1]) === maxLayer).sort())
			lines.push(`- [[${n}]]`);
		lines.push("");
	}
	return lines.join("\n");
}

/** Slugify a record id into a filename-safe basename (keeps the namespace
 *  prefix legible: "ltx:cfg-scale-7-lever" -> "ltx-cfg-scale-7-lever"). */
export function slugify(id: string): string {
	return id
		.trim()
		.replace(/[:/\\]+/g, "-") // namespace + path separators
		.replace(/[^A-Za-z0-9._-]+/g, "-")
		.replace(/-+/g, "-")
		.replace(/^-|-$/g, "")
		.toLowerCase()
		.slice(0, 80) || "untitled";
}

export function normTag(t: string): string {
	return t.trim().toLowerCase().replace(/\s+/g, "-");
}
