/**
 * Build pipeline with protection tiers.
 *
 * Tiers:
 *   bun scripts/build.ts             bundle + minify + external sourcemap
 *   bun scripts/build.ts --obfuscate + javascript-obfuscator (control-flow, strings, self-defending)
 *   bun scripts/build.ts --compile   bun --compile → standalone executable (bytecode; best)
 *   bun scripts/build.ts --all       minify → obfuscate → compile
 *
 * Output (one level up, namespaced by app name):
 *   ../dist/<app-name>/cli.js          bundled entry (minified, optionally obfuscated)
 *   ../dist/<app-name>/cli.js.map      bun sourcemap
 *   ../dist/<app-name>/cli.js.obf.map  obfuscator sourcemap (only with --obfuscate)
 *   ../dist/<app-name>/<app-name>      standalone executable (only with --compile)
 *
 * Protection strength:
 *   minify     low    names mangled + whitespace gone; trivially unminified
 *   obfuscate  medium control-flow flatten, string-array, self-defending
 *   compile    medium-low  source embedded as plaintext strings inside binary
 *
 * Run artifacts (from project root):
 *   bun ../dist/<app-name>/cli.js ext "List files"
 *   ./../dist/<app-name>/<app-name> ext "List files"
 */
import {
	existsSync,
	mkdirSync,
	rmSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { resolve, basename } from "node:path";

// Resolve app name from package.json; output goes one level up, namespaced.
const APP_NAME: string = basename(process.cwd());

const ENTRY = "src/cli.ts";
const OUTDIR = resolve(process.cwd(), "..", "..", "dist", APP_NAME);
const OUTFILE = `${OUTDIR}/cli.js`;
const MAPFILE = `${OUTFILE}.map`;
const OBFMAP = `${OUTFILE}.obf.map`;
const EXE = `${OUTDIR}/${APP_NAME}`;

const argv = process.argv.slice(2);
const DO_OBFUSCATE = argv.includes("--obfuscate") || argv.includes("--all");
const DO_COMPILE = argv.includes("--compile") || argv.includes("--all");

function clean(...files: string[]) {
	for (const f of files) if (existsSync(f)) rmSync(f);
}

function ensureOutdir() {
	if (!existsSync(OUTDIR)) mkdirSync(OUTDIR, { recursive: true });
}

/** Auto-generated warning README placed in the output dir every build. */
function writeReadme() {
	const rel = OUTDIR.replace(process.cwd() + "/", "");
	writeFileSync(
		`${OUTDIR}/README.md`,
		`# ${rel}/\n\n` +
			"Build artifacts — **NOT for distribution**. Debug only.\n\n" +
			"Generated by `bun scripts/build.ts`. If any of these files reaches a user,\n" +
			"your source is effectively exposed.\n\n" +
			"## File-by-file risk\n\n" +
			"| File | Risk |\n" +
			"|------|------|\n" +
			`| \`cli.js\` | **Low.** Minified only. Prettier + rename restores logic. Plaintext strings. |\n` +
			"| `cli.js.map` | **ZERO — this IS your source.** Embeds full `sourcesContent` for ~3,773 modules incl. every `src/*.ts`. |\n" +
			`| \`${APP_NAME}\` | **Medium-low.** Compiled executable; minified JS still embedded as plaintext strings, extractable with \`strings\`. |\n\n` +
			"## Key facts\n\n" +
			"- **Sourcemaps are debug-only.** `*.map`'s `sourcesContent` carries full original source. Never distribute.\n" +
			"- **`bun --compile` does not encrypt JS.** Source is plaintext inside the binary.\n" +
			"- For real protection, move sensitive logic to a server-side API.\n",
	);
}

// ---------- stage 1: bundle + minify + sourcemap ----------
async function stageBundle() {
	console.log(
		`▶ stage 1: bundle + minify → ${OUTDIR.replace(process.cwd() + "/", "")}`,
	);
	ensureOutdir();
	clean(OUTFILE, MAPFILE);
	const { build } = await import("bun");
	const result = await build({
		entrypoints: [ENTRY],
		outdir: OUTDIR,
		target: "bun",
		format: "esm",
		naming: "cli.js",
		minify: { whitespace: true, identifiers: true, syntax: true },
		sourcemap: "external",
		splitting: false,
	});
	if (!result.success) {
		for (const l of result.logs) console.error(l);
		process.exit(1);
	}
	console.log(`  ✓ ${OUTFILE} + ${MAPFILE}`);
	writeReadme();
}

// ---------- stage 2: obfuscate ----------
async function stageObfuscate() {
	console.log("▶ stage 2: obfuscate");
	const { default: JavaScriptObfuscator } = await import(
		"javascript-obfuscator"
	);
	const code = readFileSync(OUTFILE, "utf8");
	const out = JavaScriptObfuscator.obfuscate(code, {
		compact: true,
		controlFlowFlattening: true,
		controlFlowFlatteningThreshold: 0.75,
		deadCodeInjection: true,
		deadCodeInjectionThreshold: 0.4,
		stringArray: true,
		stringArrayEncoding: ["base64"],
		stringArrayThreshold: 0.75,
		identifierNamesGenerator: "hexadecimal",
		renameGlobals: false, // keep ESM safe
		selfDefending: true,
		disableConsoleOutput: false,
		sourceMap: true,
		sourceMapMode: "separate",
		// Regex literals containing Unicode property escapes (\p{...}) crash the
		// obfuscator's parser, so skip transforming them.
		// @ts-expect-error lib type may not expose this
		regexObfuscation: false,
	});
	clean(OBFMAP);
	writeFileSync(OUTFILE, out.getObfuscatedCode());
	writeFileSync(OBFMAP, out.getSourceMap());
	console.log(`  ✓ obfuscated ${OUTFILE} + ${OBFMAP}`);
}

// ---------- stage 3: compile to standalone executable ----------
async function stageCompile() {
	console.log("▶ stage 3: compile → standalone executable");
	clean(EXE);
	// Spawn bun so the same bun that runs this script does the compile.
	const input = DO_OBFUSCATE ? OUTFILE : ENTRY;
	const args = [
		"build",
		input,
		"--compile",
		`--outfile=${EXE}`,
		"--minify",
		...(DO_OBFUSCATE ? [] : ["--sourcemap=external"]),
	];
	const proc = Bun.spawn(["bun", ...args], {
		stdout: "inherit",
		stderr: "inherit",
	});
	const code = await proc.exited;
	if (code !== 0) {
		console.error(`  ✗ bun build --compile exited ${code}`);
		process.exit(code);
	}
	console.log(`  ✓ ${EXE}`);
}

// ---------- orchestrate ----------
if (argv.length === 0) {
	await stageBundle();
} else {
	// when obfuscating, bundle first; obfuscation mutates the bundle
	await stageBundle();
	if (DO_OBFUSCATE) {
		try {
			await stageObfuscate();
		} catch (err) {
			console.warn(`  ! obfuscation failed: ${(err as Error).message}`);
			console.warn(
				`  ! kept minified ${OUTFILE}. Use --compile for strongest protection.`,
			);
		}
	}
	if (DO_COMPILE) await stageCompile();
}
console.log("▶ done");
