export const RESOLUTION_OPTIONS = [
    '144p',
    '240p',
    '360p',
    '480p',
    '720p',
    '820p',
    '1080p',
    '1440p',
    '2160p',
    '4320p'
];

export const DEFAULT_NODE_PROPERTIES = {
    mode: "Manual",
    valueX: 512,
    valueY: 512,
    batch_size: 1,
    canvas_min_x: 0,
    canvas_max_x: 2048,
    canvas_step_x: 64,
    canvas_min_y: 0,
    canvas_max_y: 2048,
    canvas_step_y: 64,
    canvas_decimals_x: 0,
    canvas_decimals_y: 0,
    canvas_snap: true,
    canvas_dots: true,
    canvas_frame: true,
    action_slider_snap_min: 16,
    action_slider_snap_max: 256,
    action_slider_snap_step: 16,
    scaling_slider_min: 0.1,
    scaling_slider_max: 4.0,
    scaling_slider_step: 0.1,
    megapixels_slider_min: 0.5,
    megapixels_slider_max: 6.0,
    megapixels_slider_step: 0.1,
    snapValue: 64,
    upscaleValue: 1.0,
    targetResolution: 1080,
    targetMegapixels: 2.0,
    rescaleMode: "resolution",
    rescaleValue: 1.0,
    preserveScalingRatio: false,
    autoDetect: false,
    autoDetectSource: "backend",
    autoDetectWidth: 0,
    autoDetectHeight: 0,
    autoDetectPresetsJSON: "{}",
    autoFitOnChange: false,
    autoResizeOnChange: false,
    autoSnapOnChange: false,
    smartFit: false,
    selectedCategory: "Standard",
    selectedPreset: null,
    useCustomCalc: false,
    showCalcInfo: false,
    manual_slider_min_w: 64,
    manual_slider_max_w: 2048,
    manual_slider_step_w: 64,
    manual_slider_min_h: 64,
    manual_slider_max_h: 2048,
    manual_slider_step_h: 64,
    section_actions_collapsed: false,
    section_scaling_collapsed: false,
    section_autoDetect_collapsed: false,
    section_presets_collapsed: false,
    section_extraControls_collapsed: false,
    preferred_compact_height: null,
    preferred_expanded_height: null,
    dropdown_resolution_expanded: false,
    dropdown_category_expanded: false,
    dropdown_preset_expanded: false,
    preset_selector_mode: 'visual',
    customPresetsJSON: '',
};
