#!/usr/bin/env bun
//
// A wizard — walks a human through a manual procedure step by step.
// Generated by the wizard skill.
//
// Everything above the "STAGES" marker is the wizard library: do not hand-edit
// it. Author the per-step stages below the marker.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs";

// ──────────────────────────────────────────────────────────────────────────
// Wizard library — delightful, consistent UX. Identical across every wizard.
// ──────────────────────────────────────────────────────────────────────────

const isTTY = process.stdout.isTTY === true;
const C = {
  bold: (s: string) => (isTTY ? `\x1b[1m${s}\x1b[0m` : s),
  dim: (s: string) => (isTTY ? `\x1b[2m${s}\x1b[0m` : s),
  blue: (s: string) => (isTTY ? `\x1b[34m${s}\x1b[0m` : s),
  green: (s: string) => (isTTY ? `\x1b[32m${s}\x1b[0m` : s),
  yellow: (s: string) => (isTTY ? `\x1b[33m${s}\x1b[0m` : s),
};

// Author sets this at the top of the stages section.
let TOTAL_STAGES = 0;

let stageIndex = 0;
const ENV_FILE = process.env.ENV_FILE ?? ".env";
const writtenEnv: string[] = [];
const writtenSecret: string[] = [];
const skipped: string[] = [];

function clear(): void {
  if (!isTTY) return;
  process.stdout.write("\x1b[2J\x1b[3J\x1b[H");
}

// Shared line reader — queues whole lines so input that arrives ahead of a
// question (piped stdin) is never swallowed. A TTY in cooked mode echoes by
// itself, so no readline layer is needed.
const lineQueue: string[] = [];
let lineWaiter: ((line: string) => void) | undefined;
let pending = "";
let secretMode = false;

function feedLine(line: string): void {
  if (lineWaiter) {
    const waiter = lineWaiter;
    lineWaiter = undefined;
    waiter(line);
  } else {
    lineQueue.push(line);
  }
}

process.stdin.on("data", (chunk: Buffer) => {
  if (secretMode) return; // readSecret owns stdin while it's active
  pending += chunk.toString("utf8");
  let i = 0;
  while (i < pending.length) {
    const nl = pending.indexOf("\n", i);
    if (nl === -1) break;
    let end = nl;
    if (end > i && pending[end - 1] === "\r") end--;
    feedLine(pending.slice(i, end));
    i = nl + 1;
  }
  pending = pending.slice(i);
});
process.stdin.on("end", () => {
  feedLine(pending);
  pending = "";
  if (lineWaiter) feedLine(""); // exhausted input: stop blocking on it
});
process.stdin.resume();

async function readLine(prompt: string): Promise<string> {
  process.stdout.write(prompt);
  const answer = await new Promise<string>((resolve) => {
    if (lineQueue.length) resolve(lineQueue.shift() as string);
    else lineWaiter = resolve;
  });
  return answer.trim();
}

/** Hidden entry — echo off while reading. Non-TTY stdin (a pipe, a script) has
 * no echo to hide, so it falls back to a plain line read. */
async function readSecret(prompt: string): Promise<string> {
  if (process.stdin.isTTY !== true) return readLine(prompt);
  process.stdout.write(prompt);
  const buf: string[] = [];
  secretMode = true;
  process.stdin.setRawMode(true);
  process.stdin.resume();
  await new Promise<void>((resolve) => {
    const onData = (chunk: Buffer): void => {
      for (const ch of chunk.toString("utf8")) {
        if (ch === "\r" || ch === "\n") {
          process.stdin.setRawMode(false);
          process.stdin.pause();
          process.stdin.removeListener("data", onData);
          resolve();
          return;
        }
        if (ch === "\x03") process.exit(130);
        if (ch === "\x7f" || ch === "\b") buf.pop();
        else if (ch >= " ") buf.push(ch);
      }
    };
    process.stdin.on("data", onData);
  });
  secretMode = false;
  process.stdout.write("\n");
  return buf.join("");
}

/** banner "Title" — opening frame: what this wizard does. */
async function banner(title: string): Promise<void> {
  clear();
  process.stdout.write(`\n${C.bold(C.blue(`  ${title}`))}\n`);
  process.stdout.write(`${C.dim(`  ${TOTAL_STAGES} stages`)}\n\n`);
  process.stdout.write(
    `${C.dim("  You drive the browser; this wizard tells you exactly what to do and\n  captures the values you copy back. Stop any time with Ctrl-C and re-run\n  later — it remembers values already saved.")}\n`,
  );
  await pause("Ready to start?");
}

/** stage "Name" — clear the screen, then announce a stage and show progress. */
function stage(name: string): void {
  clear();
  stageIndex += 1;
  process.stdout.write(`\n${C.bold(C.blue(`▸ Stage ${stageIndex}/${TOTAL_STAGES} · ${name}`))}\n`);
}

/** say "..." — a plain instruction line. */
function say(text: string): void {
  process.stdout.write(`  ${text}\n`);
}
/** step "..." — a numbered-feeling action the human takes in the browser. */
function step(text: string): void {
  process.stdout.write(`  ${C.blue("•")} ${text}\n`);
}
function note(text: string): void {
  process.stdout.write(`  ${C.dim(text)}\n`);
}
function warn(text: string): void {
  process.stdout.write(`  ${C.yellow(`⚠ ${text}`)}\n`);
}

/** openUrl — open in the human's browser, cross-platform incl. WSL. */
function openUrl(url: string): void {
  process.stdout.write(`  ${C.green("↗ opening")} ${url}\n`);
  const tryCmds: Array<[string, string[]]> =
    process.platform === "win32"
      ? [["cmd", ["/c", "start", "", url]]]
      : [
          ["open", [url]],
          ["xdg-open", [url]],
          ["wslview", [url]],
          ["explorer.exe", [url]],
        ];
  for (const [cmd, args] of tryCmds) {
    const r = spawnSync(cmd, args, { stdio: "ignore" });
    if (!r.error) return;
  }
  warn(`couldn't open a browser — visit it manually: ${url}`);
}

/** pause "msg" — wait for the human to confirm they've done the manual part. */
async function pause(msg = "Press Enter to continue"): Promise<void> {
  await readLine(`  ${C.dim(msg)} `);
}

/** confirm "question" — y/N gate; true on yes. */
// biome-ignore lint/correctness/noUnusedVariables: library helper — authored stages below the STAGES marker call this
async function confirm(question: string): Promise<boolean> {
  const reply = await readLine(`  ${C.yellow("?")} ${question} [y/N] `);
  return /^[Yy]/.test(reply);
}

/** existing value of KEY in ENV_FILE, if any. */
function existing(key: string): string | undefined {
  if (!existsSync(ENV_FILE)) return undefined;
  const line = readFileSync(ENV_FILE, "utf8")
    .split("\n")
    .filter((l) => l.startsWith(`${key}=`))
    .pop();
  return line?.slice(key.length + 1);
}

/** ask KEY "Prompt" — read a value into a returned string. Enter keeps current. */
async function ask(key: string, prompt: string): Promise<string> {
  const current = existing(key);
  const suffix = current ? ` ${C.dim("[Enter keeps current]")}` : "";
  const input = await readLine(`  ${C.bold(prompt)}${suffix} `);
  return input === "" && current !== undefined ? current : input;
}

/** askSecret KEY "Prompt" — like ask, but input is hidden. */
async function askSecret(key: string, prompt: string): Promise<string> {
  const current = existing(key);
  const suffix = current ? ` ${C.dim("[Enter keeps current]")}` : "";
  const input = await readSecret(`  ${C.bold(prompt)}${suffix} `);
  return input === "" && current !== undefined ? current : input;
}

/** writeEnv KEY VALUE — idempotent upsert into ENV_FILE. */
function writeEnv(key: string, value: string): void {
  const lines = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, "utf8").split("\n") : [];
  const kept = lines.filter((l) => l !== "" && !l.startsWith(`${key}=`));
  kept.push(`${key}=${value}`);
  writeFileSync(`${ENV_FILE}.tmp`, `${kept.join("\n")}\n`);
  renameSync(`${ENV_FILE}.tmp`, ENV_FILE);
  writtenEnv.push(key);
  process.stdout.write(`  ${C.green("✓ wrote")} ${key} → ${ENV_FILE}\n`);
}

function ghReady(): boolean {
  return spawnSync("gh", ["auth", "status"], { stdio: "ignore" }).status === 0;
}

/** setSecret NAME VALUE — GitHub Actions repo secret via gh; warn-skip on failure. */
function setSecret(name: string, value: string): void {
  if (ghReady() && spawnSync("gh", ["secret", "set", name], { input: value, stdio: "ignore" }).status === 0) {
    writtenSecret.push(name);
    process.stdout.write(`  ${C.green("✓ set")} GitHub secret ${name}\n`);
    return;
  }
  skipped.push(`GitHub secret ${name} (set it manually: gh secret set ${name})`);
  warn(`skipped GitHub secret ${name} — gh not ready; set it later`);
}

/** setVar NAME VALUE — GitHub Actions repo variable (non-secret). */
// biome-ignore lint/correctness/noUnusedVariables: library helper — authored stages below the STAGES marker call this
function setVar(name: string, value: string): void {
  if (ghReady() && spawnSync("gh", ["variable", "set", name, "--body", value], { stdio: "ignore" }).status === 0) {
    process.stdout.write(`  ${C.green("✓ set")} GitHub variable ${name}\n`);
    return;
  }
  skipped.push(`GitHub variable ${name}`);
  warn(`skipped GitHub variable ${name} — gh not ready; set it later`);
}

/** finish — clear, then a closing summary of everything configured. */
function finish(): void {
  clear();
  process.stdin.destroy(); // release stdin so the process can exit
  process.stdout.write(`\n${C.bold(C.green("  ✓ Setup complete"))}\n`);
  if (writtenEnv.length) note(`wrote ${writtenEnv.length} value(s) to ${ENV_FILE}: ${writtenEnv.join(" ")}`);
  if (writtenSecret.length) note(`set ${writtenSecret.length} GitHub secret(s): ${writtenSecret.join(" ")}`);
  if (skipped.length) {
    process.stdout.write("\n");
    warn("still to do by hand:");
    for (const s of skipped) note(`  - ${s}`);
  }
  process.stdout.write("\n");
}

// ──────────────────────────────────────────────────────────────────────────
// STAGES — author this section. One stage() per step the human takes.
// Replace the example below. Set TOTAL_STAGES to match the stages you write.
// ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES = 1;

await banner("Stripe setup");

// ── Example stage: replace with your real steps ───────────────────────────
stage("Stripe — API keys");
say("We'll grab your Stripe test keys and store them for local dev + CI.");
openUrl("https://dashboard.stripe.com/test/apikeys");
step("On the API keys page, copy the Publishable key (starts pk_test_).");
const STRIPE_PUBLISHABLE_KEY = await ask("STRIPE_PUBLISHABLE_KEY", "Paste the publishable key:");
step("Click 'Reveal test key' on the Secret key row, then copy it.");
const STRIPE_SECRET_KEY = await askSecret("STRIPE_SECRET_KEY", "Paste the secret key:");
writeEnv("STRIPE_PUBLISHABLE_KEY", STRIPE_PUBLISHABLE_KEY);
writeEnv("STRIPE_SECRET_KEY", STRIPE_SECRET_KEY);
setSecret("STRIPE_SECRET_KEY", STRIPE_SECRET_KEY); // CI needs this one
// ──────────────────────────────────────────────────────────────────────────

finish();
