import fs from "fs";
import path from "path";
import { loadConfig, REPO_DIR } from "../lib/config";
import { RUN_PY, MLX_OUTPUT_DIR } from "../lib/paths";
import { readJsonFile } from "../lib/fsUtils";
import { subprocessManager } from "../lib/subprocess";
import { resolvePythonBin } from "../lib/pythonBin";

export async function handleModelCheckRun(_req: Request): Promise<Response> {
  const pythonBin = resolvePythonBin();
  const outputDir = MLX_OUTPUT_DIR;

  try {
    const proc = Bun.spawnSync(
      [pythonBin, RUN_PY, "check-model", "--json", "--html"],
      { stdout: "pipe", stderr: "pipe", timeout: 30_000 },
    );

    const stdout = new TextDecoder().decode(proc.stdout).trim();

    // check-model exits with code 1 when validation errors are found,
    // but the JSON output is still valid and contains error details.
    // Try parsing stdout regardless of exit code.
    if (stdout) {
      try {
        const result = JSON.parse(stdout);

        // Find the latest HTML report generated by --html
        let htmlUrl: string | null = null;
        try {
          const files = fs.readdirSync(outputDir)
            .filter((f) => f.startsWith("model-report-") && f.endsWith(".html"))
            .sort();
          if (files.length > 0) {
            htmlUrl = `/output/${files[files.length - 1]}`;
          }
        } catch { /* output dir may not exist */ }

        return Response.json({ ok: true, result, htmlUrl });
      } catch {
        // stdout wasn't valid JSON — fall through to error
      }
    }

    const stderr = new TextDecoder().decode(proc.stderr).trim();
    return Response.json({ ok: false, error: stderr || "check-model produced no output" });
  } catch (e: any) {
    return Response.json({ ok: false, error: e.message || "Failed to run check-model" });
  }
}

export async function handleModelCheckCache(_req: Request): Promise<Response> {
  const outputDir = MLX_OUTPUT_DIR;
  const cachePath = path.join(outputDir, "model-check.json");

  if (!fs.existsSync(cachePath)) {
    return Response.json({ ok: false, error: "No cached result" }, { status: 404 });
  }

  try {
    const result = readJsonFile(cachePath);
    if (!result) {
      return Response.json({ ok: false, error: "Failed to read cache" });
    }

    // Resolve the latest HTML report so the frontend can show the link
    // even after a tab switch (component remount + cache reload).
    let htmlUrl: string | null = null;
    try {
      const files = fs.readdirSync(outputDir)
        .filter((f) => f.startsWith("model-report-") && f.endsWith(".html"))
        .sort();
      if (files.length > 0) {
        htmlUrl = `/output/${files[files.length - 1]}`;
      }
    } catch { /* output dir may not exist */ }

    return Response.json({ ok: true, result, htmlUrl });
  } catch (e: any) {
    return Response.json({ ok: false, error: "Failed to read cache: " + (e.message || String(e)) });
  }
}

/** Async model check — returns job ID for WebSocket streaming. */
export function handleModelCheckScan(_req: Request): Response {
  try {
    const jobId = subprocessManager.spawn("check-model", ["--json", "--html"]);
    return Response.json({ ok: true, jobId });
  } catch (e: any) {
    return Response.json({ ok: false, error: e.message || "Failed to start scan" });
  }
}
