[pytest]
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q --tb=short -ra --strict-markers
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__:DeprecationWarning
    ignore:invalid escape sequence.*:SyntaxWarning
