/**
 * Build pipeline with protection tiers for bun-pi-agent-cli.
 *
 * Tiers:
 *   bun scripts/build.ts             bundle + minify (NO sourcemap by default)
 *   bun scripts/build.ts --sourcemap  also emit the external sourcemap (.map)
 *   bun scripts/build.ts --obfuscate + javascript-obfuscator (control-flow, strings, self-defending)
 *   bun scripts/build.ts --compile   bun --compile → standalone executable
 *   bun scripts/build.ts --all       minify → obfuscate → compile
 *
 * Sourcemap is OPT-IN: the .map embeds full original source (sourcesContent)
 * and is never shipped — it is debug-only. Default off; pass --sourcemap for
 * in-place bundle debugging. Aligns with pi-agent/scripts/build.ts.
 *
 * Output (one level up, namespaced by package name):
 *   ../dist/<pkg-name>/cli.js          bundled entry (minified, optionally obfuscated)
 *   ../dist/<pkg-name>/cli.js.map      bun sourcemap
 *   ../dist/<pkg-name>/cli.js.obf.map  obfuscator sourcemap (only with --obfuscate)
 *   ../dist/<pkg-name>/<pkg-name>      standalone executable (only with --compile)
 *
 * The bundle is **self-contained**: the pi-obsidian extension is imported as
 * an inline factory (src/sessions/shared.ts), so no external package path or
 * `.pi/settings.json` is needed at runtime.
 *
 * Protection strength:
 *   minify     low    names mangled + whitespace gone; trivially unminified
 *   obfuscate  medium control-flow flatten, string-array, self-defending
 *   compile    medium-low  source embedded as plaintext strings inside binary
 */
import {
	appendFileSync,
	existsSync,
	mkdirSync,
	rmSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { basename, resolve } from "node:path";

// Resolve app name from the package directory name (e.g. bun-apps/pi-agent-cli
// → "pi-agent-cli"). Output goes two levels up to the repo-root dist/, so the
// dist path mirrors the source dir: dist/<app-name>/.
const APP_NAME: string = basename(process.cwd());

const ENTRY = "src/cli.ts";
const OUTDIR = resolve(process.cwd(), "..", "..", "dist", APP_NAME);
const OUTFILE = `${OUTDIR}/cli.js`;
const MAPFILE = `${OUTFILE}.map`;
const OBFMAP = `${OUTFILE}.obf.map`;
const EXE = `${OUTDIR}/${APP_NAME}`;

const argv = process.argv.slice(2);
const DO_OBFUSCATE = argv.includes("--obfuscate") || argv.includes("--all");
const DO_COMPILE = argv.includes("--compile") || argv.includes("--all");
// Sourcemap is opt-in (see file header): the .map embeds full source and is
// never shipped. Default off; pass --sourcemap for in-place bundle debugging.
const WITH_SOURCEMAP = argv.includes("--sourcemap");

function clean(...files: string[]) {
	for (const f of files) if (existsSync(f)) rmSync(f);
}

function ensureOutdir() {
	if (!existsSync(OUTDIR)) mkdirSync(OUTDIR, { recursive: true });
}

/** Auto-generated warning README placed in the output dir every build. */
function writeReadme() {
	const rel = OUTDIR.replace(process.cwd() + "/", "");
	writeFileSync(
		`${OUTDIR}/README.md`,
		`# ${rel}/\n\n` +
			"Build artifacts — **NOT for distribution**. Debug only.\n\n" +
			"Generated by `bun scripts/build.ts`. If any of these files reaches a user,\n" +
			"your source is effectively exposed.\n\n" +
			"## File-by-file risk\n\n" +
			"| File | Risk |\n" +
			"|------|------|\n" +
			`| \`cli.js\` | **Low.** Minified only. Plaintext strings. |\n` +
			"| `cli.js.map` | **ZERO — this IS your source.** Embeds full `sourcesContent`. |\n" +
			`| \`${APP_NAME}\` | **Medium-low.** Compiled executable; minified JS still embedded as plaintext strings. |\n\n` +
			"## Key facts\n\n" +
			"- **Sourcemaps are debug-only.** `*.map`'s `sourcesContent` carries full original source. Never distribute.\n" +
			"- **`bun --compile` does not encrypt JS.** Source is plaintext inside the binary.\n" +
			"- For real protection, move sensitive logic to a server-side API.\n",
	);
}

// ---------- stage 1: bundle + minify + sourcemap ----------
async function stageBundle() {
	console.log(
		`▶ stage 1: bundle + minify → ${OUTDIR.replace(process.cwd() + "/", "")}`,
	);
	ensureOutdir();
	// Clear every possible output artifact so a plain build never leaves stale
	// files from a previous --obfuscate / --compile run (an out-of-date exe or
	// obf sourcemap lingering next to a freshly rebuilt cli.js is misleading).
	clean(OUTFILE, MAPFILE, OBFMAP, EXE);
	const { build } = await import("bun");
	const result = await build({
		entrypoints: [ENTRY],
		outdir: OUTDIR,
		target: "bun",
		format: "esm",
		naming: "cli.js",
		minify: { whitespace: true, identifiers: true, syntax: true },
		sourcemap: WITH_SOURCEMAP ? "external" : "none",
		splitting: false,
	});
	if (!result.success) {
		for (const l of result.logs) console.error(l);
		process.exit(1);
	}
	// Only append the sourceMappingURL comment when a map was actually emitted;
	// otherwise the comment points at a nonexistent file.
	if (WITH_SOURCEMAP) {
		const mapName = basename(MAPFILE);
		appendFileSync(OUTFILE, `\n//# sourceMappingURL=${mapName}\n`);
		console.log(`  ✓ ${OUTFILE} + ${MAPFILE} (sourceMappingURL linked)`);
	} else {
		console.log(`  ✓ ${OUTFILE}`);
	}
	writeReadme();
}

/**
 * Loud, unmissable warning that the sourcemap is present. The external `.map`
 * embeds the FULL original source (`sourcesContent`), so a debug build has
 * complete traceability but ships your source. Print this on every debug build
 * so it is never accidentally deployed to the real run directory.
 */
function warnSourcemapDebug(): void {
	const rel = OUTDIR.replace(process.cwd() + "/", "");
	console.log("");
	console.log(
		"⚠️   DEBUG BUILD — sourcemap IS present and linked to the bundle.   ⚠️",
	);
	console.log(
		`    ${rel}/cli.js.map  contains the FULL original source (sourcesContent).`,
	);
	console.log(
		"    The bundle has full debug capability, but deploying this file",
	);
	console.log(
		"    exposes your source. REMOVE the sourcemap before real deployment:",
	);
	console.log(`      rm  <run-dir>/cli.js.map`);
	console.log(
		`      sed -i '' '/\\/\\/# sourceMappingURL=/d' <run-dir>/cli.js   # macOS`,
	);
	console.log(
		`      sed -i    '/\\/\\/# sourceMappingURL=/d' <run-dir>/cli.js   # Linux`,
	);
	console.log(
		"    (Or build with `--compile`/`--obfuscate` and distribute that instead.)",
	);
	console.log("");
}

// ---------- stage 2: obfuscate ----------
async function stageObfuscate() {
	console.log("▶ stage 2: obfuscate");
	const { default: JavaScriptObfuscator } = await import(
		"javascript-obfuscator"
	);
	const code = readFileSync(OUTFILE, "utf8");
	const out = JavaScriptObfuscator.obfuscate(code, {
		compact: true,
		controlFlowFlattening: true,
		controlFlowFlatteningThreshold: 0.75,
		deadCodeInjection: true,
		deadCodeInjectionThreshold: 0.4,
		stringArray: true,
		stringArrayEncoding: ["base64"],
		stringArrayThreshold: 0.75,
		identifierNamesGenerator: "hexadecimal",
		renameGlobals: false, // keep ESM safe
		selfDefending: true,
		disableConsoleOutput: false,
		sourceMap: true,
		sourceMapMode: "separate",
		// javascript-obfuscator's regex transformer is brittle on non-trivial
		// patterns (pi-obsidian carries complex wiki-link/frontmatter regexes)
		// and has crashed on them in the past, so leave regex literals intact.
		regexObfuscation: false,
	});
	clean(OBFMAP);
	writeFileSync(OUTFILE, out.getObfuscatedCode());
	writeFileSync(OBFMAP, out.getSourceMap());
	console.log(`  ✓ obfuscated ${OUTFILE} + ${OBFMAP}`);
}

// ---------- stage 3: compile to standalone executable ----------
async function stageCompile() {
	console.log("▶ stage 3: compile → standalone executable");
	clean(EXE);
	const input = DO_OBFUSCATE ? OUTFILE : ENTRY;
	const args = [
		"build",
		input,
		"--compile",
		`--outfile=${EXE}`,
		"--minify",
		...(DO_OBFUSCATE ? [] : WITH_SOURCEMAP ? ["--sourcemap=external"] : []),
	];
	const proc = Bun.spawn(["bun", ...args], {
		stdout: "inherit",
		stderr: "inherit",
	});
	const code = await proc.exited;
	if (code !== 0) {
		console.error(`  ✗ bun build --compile exited ${code}`);
		process.exit(code);
	}
	console.log(`  ✓ ${EXE}`);
}

// ---------- pre-flight: workspace deps must be linked ----------
// A stale root `bun install` leaves `@repo/*` workspace deps un-symlinked, so
// the bundler can't resolve their bare specifiers → hard build failure or a
// silently broken bundle. Fail loudly with an actionable fix instead.
function assertWorkspaceDeps(): void {
  const pj = JSON.parse(readFileSync("package.json", "utf8")) as {
    dependencies?: Record<string, string>;
    peerDependencies?: Record<string, string>;
  };
  const all = { ...pj.dependencies, ...pj.peerDependencies };
  const ws = Object.keys(all).filter((d) => d.startsWith("@repo/"));
  const missing = ws.filter((d) => !existsSync(`node_modules/${d}`));
  if (missing.length > 0) {
    console.error(
      `\n✗ missing workspace symlinks: ${missing.join(", ")}\n` +
        `  The monorepo's node_modules is stale. Fix:\n` +
        `    bun install            # at the REPO ROOT (not here)\n` +
        `    bun scripts/build.ts   # then rebuild\n`,
    );
    process.exit(1);
  }
}

// ---------- orchestrate ----------
assertWorkspaceDeps();
if (argv.length === 0) {
	await stageBundle();
} else {
	await stageBundle();
	if (DO_OBFUSCATE) {
		try {
			await stageObfuscate();
		} catch (err) {
			console.warn(`  ! obfuscation failed: ${(err as Error).message}`);
			console.warn(
				`  ! kept minified ${OUTFILE}. Use --compile for strongest protection.`,
			);
		}
	}
	if (DO_COMPILE) await stageCompile();
}
// Warn about the sourcemap ONLY when one was actually produced (opt-in).
if (WITH_SOURCEMAP && existsSync(MAPFILE)) warnSourcemapDebug();
console.log("▶ done");
